/**
 * Lote 292 -- los catalogos de cuentas de las SEIS empresas, medidos en PRODUCCION
 * el 2026-10-04 (2026-10-05 03:23:47.057686+00, solo lectura, transaccion `read only`,
 * `scratch/_to_delete/medir_292.ts`). Congelados aqui para que el banco ejecute
 * `planParaCompletar` contra lo que hay de verdad, sin red ni base.
 *
 * Por cuenta: [codigo, nombre, tipo, naturaleza, transaccional, estado, renglones].
 * `claves`: las claves de Cuentas Puente ya enlazadas, como `clave=codigo`.
 * No lleva identificadores: el banco les pone uno derivado del codigo.
 */
export type FilaMedida = [string, string, string, string, boolean, string, number];
export interface EmpresaMedida { catalogo: FilaMedida[]; claves: string[] }

export const MEDIDO_EL = '2026-10-05 03:23:47.057686+00';

export const CATALOGOS_MEDIDOS: Record<string, EmpresaMedida> = {
  "Artalum": {
    catalogo: [
      ["1","Activos","asset","debit",false,"active",0],
      ["1.1","Activo Corriente","asset","debit",false,"active",0],
      ["1.1.01","Efectivo en Caja y Bancos","asset","debit",false,"active",0],
      ["1.1.01.01","Caja General","asset","debit",true,"active",0],
      ["1.1.01.02","Banco Popular","asset","debit",true,"active",0],
      ["1.1.01.03","Banco de Reservas","asset","debit",true,"active",0],
      ["1.1.02","Cuentas por Cobrar","asset","debit",false,"active",0],
      ["1.1.02.01","Cuentas por Cobrar Clientes","asset","debit",true,"active",0],
      ["1.1.02.02","Otras Cuentas por Cobrar","asset","debit",true,"active",0],
      ["1.1.03","Inventarios","asset","debit",false,"active",0],
      ["1.1.03.01","Inventario de Mercancía","asset","debit",true,"active",0],
      ["1.1.04","Impuestos Anticipados","asset","debit",false,"active",0],
      ["1.1.04.01","ITBIS Pagado en Compras","asset","debit",true,"active",0],
      ["1.1.04.02","Anticipos de ISR","asset","debit",true,"active",0],
      ["1.1.04.03","ITBIS Retenido por Clientes","asset","debit",true,"active",0],
      ["1.1.04.04","Otras Retenciones por Clientes","asset","debit",true,"active",0],
      ["1.2","Activos Fijos","asset","debit",false,"active",0],
      ["1.2.01","Propiedades, Planta y Equipo","asset","debit",false,"active",0],
      ["1.2.01.01","Equipos de Transporte","asset","debit",true,"active",0],
      ["1.2.01.02","Equipos de Oficina","asset","debit",true,"active",0],
      ["1.2.01.03","Depreciación Acumulada","asset","credit",true,"active",0],
      ["2","Pasivos","liability","credit",false,"active",0],
      ["2.1","Pasivos Corrientes","liability","credit",false,"active",0],
      ["2.1.01","Cuentas por Pagar","liability","credit",false,"active",0],
      ["2.1.01.01","Cuentas por Pagar Proveedores","liability","credit",true,"active",0],
      ["2.1.01.02","Otras Cuentas por Pagar","liability","credit",true,"active",0],
      ["2.1.01.03","Tarjetas de Crédito por Pagar","liability","credit",true,"active",0],
      ["2.1.02","Impuestos Retenidos y por Pagar","liability","credit",false,"active",0],
      ["2.1.02.01","ITBIS Cobrado en Ventas","liability","credit",true,"active",0],
      ["2.1.02.02","ITBIS Retenido por Pagar","liability","credit",true,"active",0],
      ["2.1.02.03","Retenciones de ISR por Pagar","liability","credit",true,"active",0],
      ["3","Patrimonio","equity","credit",false,"active",0],
      ["3.1","Capital Social","equity","credit",false,"active",0],
      ["3.1.01","Capital Suscrito y Pagado","equity","credit",true,"active",0],
      ["3.2","Resultados","equity","credit",false,"active",0],
      ["3.2.01","Utilidades Acumuladas","equity","credit",true,"active",0],
      ["4","Ingresos","revenue","credit",false,"active",0],
      ["4.1","Ingresos Operacionales","revenue","credit",false,"active",0],
      ["4.1.01","Ventas de Mercancías","revenue","credit",true,"active",0],
      ["4.1.02","Ventas de Servicios","revenue","credit",true,"active",0],
      ["5","Costos","expense","debit",false,"active",0],
      ["5.1","Costos de Ventas","expense","debit",false,"active",0],
      ["5.1.01","Costo de Ventas Mercancías","expense","debit",true,"active",0],
      ["5.1.02","Otros Impuestos y Tasas","expense","debit",true,"active",0],
      ["6","Gastos","expense","debit",false,"active",0],
      ["6.1","Gastos Operacionales","expense","debit",false,"active",0],
      ["6.1.01","Gastos de Personal","expense","debit",false,"active",0],
      ["6.1.01.01","Sueldos y Salarios","expense","debit",true,"active",0],
      ["6.1.01.02","Retenciones TSS (SFS/AFP/TSS)","expense","debit",true,"active",0],
      ["6.1.02","Gastos Administrativos","expense","debit",false,"active",0],
      ["6.1.02.01","Gastos de Energía Eléctrica","expense","debit",true,"active",0],
      ["6.1.02.02","Gastos de Teléfono e Internet","expense","debit",true,"active",0],
      ["6.1.02.03","Gastos de Combustible y Transporte","expense","debit",true,"active",0],
      ["6.1.02.04","Alquileres / Arrendamientos","expense","debit",true,"active",0],
      ["6.1.02.05","Reparación y Mantenimiento","expense","debit",true,"active",0],
      ["6.1.02.06","Gastos Diversos","expense","debit",true,"active",0],
    ],
    claves: ["accounts_receivable=1.1.02.01","bank=1.1.01.02","cash=1.1.01.01","cost_of_goods_sold=5.1.01","credit_card_payable=2.1.01.03","inventory=1.1.03.01","isr_retention_receivable=1.1.04.02","isr_withholding_payable=2.1.02.03","itbis_purchases=1.1.04.01","itbis_retention_receivable=1.1.04.03","itbis_sales=2.1.02.01","itbis_withholding_payable=2.1.02.02","other_retention_receivable=1.1.04.04","purchase_itbis_paid=1.1.04.01","purchase_other_taxes=5.1.02","sales_revenue=4.1.01","supplier_payable=2.1.01.01"],
  },
  "D'JIMENEZ Puertas Y Ventanas": {
    catalogo: [
      ["1","Activos","asset","debit",false,"active",0],
      ["1.1","Activo Corriente","asset","debit",false,"active",0],
      ["1.1.01","Efectivo en Caja y Bancos","asset","debit",false,"active",0],
      ["1.1.01.01","Caja General","asset","debit",true,"active",0],
      ["1.1.01.02","Banco Popular","asset","debit",true,"active",0],
      ["1.1.01.03","Banco de Reservas","asset","debit",true,"active",0],
      ["1.1.02","Cuentas por Cobrar","asset","debit",false,"active",0],
      ["1.1.02.01","Cuentas por Cobrar Clientes","asset","debit",true,"active",0],
      ["1.1.02.02","Otras Cuentas por Cobrar","asset","debit",true,"active",0],
      ["1.1.03","Inventarios","asset","debit",false,"active",0],
      ["1.1.03.01","Inventario de Mercancía","asset","debit",true,"active",0],
      ["1.1.04","Impuestos Anticipados","asset","debit",false,"active",0],
      ["1.1.04.01","ITBIS Pagado en Compras","asset","debit",true,"active",0],
      ["1.1.04.02","Anticipos de ISR","asset","debit",true,"active",0],
      ["1.1.04.03","ITBIS Retenido por Clientes","asset","debit",true,"active",0],
      ["1.1.04.04","Otras Retenciones por Clientes","asset","debit",true,"active",0],
      ["1.2","Activos Fijos","asset","debit",false,"active",0],
      ["1.2.01","Propiedades, Planta y Equipo","asset","debit",false,"active",0],
      ["1.2.01.01","Equipos de Transporte","asset","debit",true,"active",0],
      ["1.2.01.02","Equipos de Oficina","asset","debit",true,"active",0],
      ["1.2.01.03","Depreciación Acumulada","asset","credit",true,"active",0],
      ["2","Pasivos","liability","credit",false,"active",0],
      ["2.1","Pasivos Corrientes","liability","credit",false,"active",0],
      ["2.1.01","Cuentas por Pagar","liability","credit",false,"active",0],
      ["2.1.01.01","Cuentas por Pagar Proveedores","liability","credit",true,"active",0],
      ["2.1.01.02","Otras Cuentas por Pagar","liability","credit",true,"active",0],
      ["2.1.01.03","Tarjetas de Crédito por Pagar","liability","credit",true,"active",0],
      ["2.1.02","Impuestos Retenidos y por Pagar","liability","credit",false,"active",0],
      ["2.1.02.01","ITBIS Cobrado en Ventas","liability","credit",true,"active",0],
      ["2.1.02.02","ITBIS Retenido por Pagar","liability","credit",true,"active",0],
      ["2.1.02.03","Retenciones de ISR por Pagar","liability","credit",true,"active",0],
      ["3","Patrimonio","equity","credit",false,"active",0],
      ["3.1","Capital Social","equity","credit",false,"active",0],
      ["3.1.01","Capital Suscrito y Pagado","equity","credit",true,"active",0],
      ["3.2","Resultados","equity","credit",false,"active",0],
      ["3.2.01","Utilidades Acumuladas","equity","credit",true,"active",0],
      ["4","Ingresos","revenue","credit",false,"active",0],
      ["4.1","Ingresos Operacionales","revenue","credit",false,"active",0],
      ["4.1.01","Ventas de Mercancías","revenue","credit",true,"active",0],
      ["4.1.02","Ventas de Servicios","revenue","credit",true,"active",0],
      ["5","Costos","expense","debit",false,"active",0],
      ["5.1","Costos de Ventas","expense","debit",false,"active",0],
      ["5.1.01","Costo de Ventas Mercancías","expense","debit",true,"active",0],
      ["5.1.02","Otros Impuestos y Tasas","expense","debit",true,"active",0],
      ["6","Gastos","expense","debit",false,"active",0],
      ["6.1","Gastos Operacionales","expense","debit",false,"active",0],
      ["6.1.01","Gastos de Personal","expense","debit",false,"active",0],
      ["6.1.01.01","Sueldos y Salarios","expense","debit",true,"active",0],
      ["6.1.01.02","Retenciones TSS (SFS/AFP/TSS)","expense","debit",true,"active",0],
      ["6.1.02","Gastos Administrativos","expense","debit",false,"active",0],
      ["6.1.02.01","Gastos de Energía Eléctrica","expense","debit",true,"active",0],
      ["6.1.02.02","Gastos de Teléfono e Internet","expense","debit",true,"active",0],
      ["6.1.02.03","Gastos de Combustible y Transporte","expense","debit",true,"active",0],
      ["6.1.02.04","Alquileres / Arrendamientos","expense","debit",true,"active",0],
      ["6.1.02.05","Reparación y Mantenimiento","expense","debit",true,"active",0],
      ["6.1.02.06","Gastos Diversos","expense","debit",true,"active",0],
    ],
    claves: ["accounts_receivable=1.1.02.01","bank=1.1.01.02","cash=1.1.01.01","cost_of_goods_sold=5.1.01","credit_card_payable=2.1.01.03","inventory=1.1.03.01","isr_retention_receivable=1.1.04.02","isr_withholding_payable=2.1.02.03","itbis_purchases=1.1.04.01","itbis_retention_receivable=1.1.04.03","itbis_sales=2.1.02.01","itbis_withholding_payable=2.1.02.02","other_retention_receivable=1.1.04.04","purchase_itbis_paid=1.1.04.01","purchase_other_taxes=5.1.02","sales_revenue=4.1.01","supplier_payable=2.1.01.01"],
  },
  "Empresa de Prueba": {
    catalogo: [
      ["1","Activos","asset","debit",false,"active",0],
      ["1.1","Activo Corriente","asset","debit",false,"active",0],
      ["1.1.01","Efectivo en Caja y Bancos","asset","debit",false,"active",0],
      ["1.1.01.01","Caja General","asset","debit",true,"active",0],
      ["1.1.01.02","Banco Popular","asset","debit",true,"active",0],
      ["1.1.01.03","Banco de Reservas","asset","debit",true,"active",0],
      ["1.1.02","Cuentas por Cobrar","asset","debit",false,"active",0],
      ["1.1.02.01","Cuentas por Cobrar Clientes","asset","debit",true,"active",0],
      ["1.1.02.02","Otras Cuentas por Cobrar","asset","debit",true,"active",0],
      ["1.1.03","Inventarios","asset","debit",false,"active",0],
      ["1.1.03.01","Inventario de Mercancía","asset","debit",true,"active",0],
      ["1.1.04","Impuestos Anticipados","asset","debit",false,"active",0],
      ["1.1.04.01","ITBIS Pagado en Compras","asset","debit",true,"active",0],
      ["1.1.04.02","Anticipos de ISR","asset","debit",true,"active",0],
      ["1.1.04.03","ITBIS Retenido por Clientes","asset","debit",true,"active",0],
      ["1.1.04.04","Otras Retenciones por Clientes","asset","debit",true,"active",0],
      ["1.1.08","ITBIS Pagado en Compras","asset","debit",true,"active",0],
      ["1.2","Activos Fijos","asset","debit",false,"active",0],
      ["1.2.01","Propiedades, Planta y Equipo","asset","debit",false,"active",0],
      ["1.2.01.01","Equipos de Transporte","asset","debit",true,"active",0],
      ["1.2.01.02","Equipos de Oficina","asset","debit",true,"active",0],
      ["1.2.01.03","Depreciación Acumulada","asset","credit",true,"active",0],
      ["2","Pasivos","liability","credit",false,"active",0],
      ["2.1","Pasivos Corrientes","liability","credit",false,"active",0],
      ["2.1.01","Cuentas por Pagar","liability","credit",false,"active",0],
      ["2.1.01.01","Cuentas por Pagar Proveedores","liability","credit",true,"active",0],
      ["2.1.01.02","Otras Cuentas por Pagar","liability","credit",true,"active",0],
      ["2.1.01.03","Tarjetas de Crédito por Pagar","liability","credit",true,"active",0],
      ["2.1.02","Impuestos Retenidos y por Pagar","liability","credit",false,"active",0],
      ["2.1.02.01","ITBIS Cobrado en Ventas","liability","credit",true,"active",0],
      ["2.1.02.02","ITBIS Retenido por Pagar","liability","credit",true,"active",0],
      ["2.1.02.03","Retenciones de ISR por Pagar","liability","credit",true,"active",0],
      ["3","Patrimonio","equity","credit",false,"active",0],
      ["3.1","Capital Social","equity","credit",false,"active",0],
      ["3.1.01","Capital Suscrito y Pagado","equity","credit",true,"active",0],
      ["3.2","Resultados","equity","credit",false,"active",0],
      ["3.2.01","Utilidades Acumuladas","equity","credit",true,"active",0],
      ["4","Ingresos","revenue","credit",false,"active",0],
      ["4.1","Ingresos Operacionales","revenue","credit",false,"active",0],
      ["4.1.01","Ventas de Mercancías","revenue","credit",true,"active",0],
      ["4.1.02","Ventas de Servicios","revenue","credit",true,"active",0],
      ["5","Costos","expense","debit",false,"active",0],
      ["5.1","Costos de Ventas","expense","debit",false,"active",0],
      ["5.1.01","Costo de Ventas Mercancías","expense","debit",true,"active",0],
      ["5.1.02","Otros Impuestos y Tasas","expense","debit",true,"active",0],
      ["6","Gastos","expense","debit",false,"active",0],
      ["6.1","Gastos Operacionales","expense","debit",false,"active",0],
      ["6.1.01","Gastos de Personal","expense","debit",false,"active",0],
      ["6.1.01.01","Sueldos y Salarios","expense","debit",true,"active",0],
      ["6.1.01.02","Retenciones TSS (SFS/AFP/TSS)","expense","debit",true,"active",0],
      ["6.1.02","Gastos Administrativos","expense","debit",false,"active",0],
      ["6.1.02.01","Gastos de Energía Eléctrica","expense","debit",true,"active",0],
      ["6.1.02.02","Gastos de Teléfono e Internet","expense","debit",true,"active",0],
      ["6.1.02.03","Gastos de Combustible y Transporte","expense","debit",true,"active",0],
      ["6.1.02.04","Alquileres / Arrendamientos","expense","debit",true,"active",0],
      ["6.1.02.05","Reparación y Mantenimiento","expense","debit",true,"active",0],
      ["6.1.02.06","Gastos Diversos","expense","debit",true,"active",0],
    ],
    claves: ["accounts_receivable=1.1.02.01","bank=1.1.01.02","cash=1.1.01.01","cost_of_goods_sold=5.1.01","credit_card_payable=2.1.01.03","inventory=1.1.03.01","isr_retention_receivable=1.1.04.02","isr_withholding_payable=2.1.02.03","itbis_purchases=1.1.04.01","itbis_retention_receivable=1.1.04.03","itbis_sales=2.1.02.01","itbis_withholding_payable=2.1.02.02","other_retention_receivable=1.1.04.04","purchase_itbis_paid=1.1.04.01","purchase_other_taxes=5.1.02","sales_revenue=4.1.01","supplier_payable=2.1.01.01"],
  },
  "J'EDWARD Puertas Y Ventanas": {
    catalogo: [
      ["1","Activos","asset","debit",false,"active",0],
      ["1.1","Activo Corriente","asset","debit",false,"active",0],
      ["1.1.01","Efectivo en Caja y Bancos","asset","debit",false,"active",0],
      ["1.1.01.01","Caja General","asset","debit",true,"active",0],
      ["1.1.01.02","Banco Popular","asset","debit",true,"active",0],
      ["1.1.01.03","Banco de Reservas","asset","debit",true,"active",0],
      ["1.1.02","Cuentas por Cobrar","asset","debit",false,"active",0],
      ["1.1.02.01","Cuentas por Cobrar Clientes","asset","debit",true,"active",0],
      ["1.1.02.02","Otras Cuentas por Cobrar","asset","debit",true,"active",0],
      ["1.1.03","Inventarios","asset","debit",false,"active",0],
      ["1.1.03.01","Inventario de Mercancía","asset","debit",true,"active",0],
      ["1.1.04","Impuestos Anticipados","asset","debit",false,"active",0],
      ["1.1.04.01","ITBIS Pagado en Compras","asset","debit",true,"active",0],
      ["1.1.04.02","Anticipos de ISR","asset","debit",true,"active",0],
      ["1.1.04.03","ITBIS Retenido por Clientes","asset","debit",true,"active",0],
      ["1.1.04.04","Otras Retenciones por Clientes","asset","debit",true,"active",0],
      ["1.2","Activos Fijos","asset","debit",false,"active",0],
      ["1.2.01","Propiedades, Planta y Equipo","asset","debit",false,"active",0],
      ["1.2.01.01","Equipos de Transporte","asset","debit",true,"active",0],
      ["1.2.01.02","Equipos de Oficina","asset","debit",true,"active",0],
      ["1.2.01.03","Depreciación Acumulada","asset","credit",true,"active",0],
      ["2","Pasivos","liability","credit",false,"active",0],
      ["2.1","Pasivos Corrientes","liability","credit",false,"active",0],
      ["2.1.01","Cuentas por Pagar","liability","credit",false,"active",0],
      ["2.1.01.01","Cuentas por Pagar Proveedores","liability","credit",true,"active",0],
      ["2.1.01.02","Otras Cuentas por Pagar","liability","credit",true,"active",0],
      ["2.1.01.03","Tarjetas de Crédito por Pagar","liability","credit",true,"active",0],
      ["2.1.02","Impuestos Retenidos y por Pagar","liability","credit",false,"active",0],
      ["2.1.02.01","ITBIS Cobrado en Ventas","liability","credit",true,"active",0],
      ["2.1.02.02","ITBIS Retenido por Pagar","liability","credit",true,"active",0],
      ["2.1.02.03","Retenciones de ISR por Pagar","liability","credit",true,"active",0],
      ["3","Patrimonio","equity","credit",false,"active",0],
      ["3.1","Capital Social","equity","credit",false,"active",0],
      ["3.1.01","Capital Suscrito y Pagado","equity","credit",true,"active",0],
      ["3.2","Resultados","equity","credit",false,"active",0],
      ["3.2.01","Utilidades Acumuladas","equity","credit",true,"active",0],
      ["4","Ingresos","revenue","credit",false,"active",0],
      ["4.1","Ingresos Operacionales","revenue","credit",false,"active",0],
      ["4.1.01","Ventas de Mercancías","revenue","credit",true,"active",0],
      ["4.1.02","Ventas de Servicios","revenue","credit",true,"active",0],
      ["5","Costos","expense","debit",false,"active",0],
      ["5.1","Costos de Ventas","expense","debit",false,"active",0],
      ["5.1.01","Costo de Ventas Mercancías","expense","debit",true,"active",0],
      ["5.1.02","Otros Impuestos y Tasas","expense","debit",true,"active",0],
      ["6","Gastos","expense","debit",false,"active",0],
      ["6.1","Gastos Operacionales","expense","debit",false,"active",0],
      ["6.1.01","Gastos de Personal","expense","debit",false,"active",0],
      ["6.1.01.01","Sueldos y Salarios","expense","debit",true,"active",0],
      ["6.1.01.02","Retenciones TSS (SFS/AFP/TSS)","expense","debit",true,"active",0],
      ["6.1.02","Gastos Administrativos","expense","debit",false,"active",0],
      ["6.1.02.01","Gastos de Energía Eléctrica","expense","debit",true,"active",0],
      ["6.1.02.02","Gastos de Teléfono e Internet","expense","debit",true,"active",0],
      ["6.1.02.03","Gastos de Combustible y Transporte","expense","debit",true,"active",0],
      ["6.1.02.04","Alquileres / Arrendamientos","expense","debit",true,"active",0],
      ["6.1.02.05","Reparación y Mantenimiento","expense","debit",true,"active",0],
      ["6.1.02.06","Gastos Diversos","expense","debit",true,"active",0],
    ],
    claves: ["accounts_receivable=1.1.02.01","bank=1.1.01.02","cash=1.1.01.01","cost_of_goods_sold=5.1.01","credit_card_payable=2.1.01.03","inventory=1.1.03.01","isr_retention_receivable=1.1.04.02","isr_withholding_payable=2.1.02.03","itbis_purchases=1.1.04.01","itbis_retention_receivable=1.1.04.03","itbis_sales=2.1.02.01","itbis_withholding_payable=2.1.02.02","other_retention_receivable=1.1.04.04","purchase_itbis_paid=1.1.04.01","purchase_other_taxes=5.1.02","sales_revenue=4.1.01","supplier_payable=2.1.01.01"],
  },
  "Latin Doors S.R.L": {
    catalogo: [
      ["1","Activos","asset","debit",false,"active",0],
      ["1.1","Activo Corriente","asset","debit",false,"active",0],
      ["1.1.01","Efectivo en Caja y Bancos","asset","debit",false,"active",111],
      ["1.1.01.01","Caja General","asset","debit",true,"active",59],
      ["1.1.01.02","Banco Popular","asset","debit",true,"active",0],
      ["1.1.01.03","Banco de Reservas","asset","debit",true,"active",6],
      ["1.1.01.04","Scotiabank","asset","debit",true,"active",6],
      ["1.1.02","Cuentas por Cobrar","asset","debit",false,"active",66],
      ["1.1.02.01","Cuentas por Cobrar Clientes","asset","debit",true,"active",30],
      ["1.1.02.02","Otras Cuentas por Cobrar","asset","debit",true,"active",0],
      ["1.1.03","Inventarios","asset","debit",false,"active",0],
      ["1.1.03.01","Inventario de Mercancía","asset","debit",true,"active",30],
      ["1.1.04","Impuestos Anticipados","asset","debit",false,"active",0],
      ["1.1.04.01","ITBIS Pagado en Compras","asset","debit",true,"active",0],
      ["1.1.04.02","Anticipos de ISR","asset","debit",true,"active",0],
      ["1.1.04.03","ITBIS Retenido por Clientes","asset","debit",true,"active",0],
      ["1.1.04.04","Otras Retenciones por Clientes","asset","debit",true,"active",0],
      ["1.1.06","Inventario de Mercancía","asset","debit",true,"active",12],
      ["1.1.08","ITBIS Pagado en Compras","asset","debit",true,"active",116],
      ["1.2","Activos Fijos","asset","debit",false,"active",0],
      ["1.2.01","Propiedades, Planta y Equipo","asset","debit",false,"active",0],
      ["1.2.01.01","Equipos de Transporte","asset","debit",true,"active",0],
      ["1.2.01.02","Equipos de Oficina","asset","debit",true,"active",0],
      ["1.2.01.03","Depreciación Acumulada","asset","credit",true,"active",0],
      ["2","Pasivos","liability","credit",false,"active",0],
      ["2.1","Pasivos Corrientes","liability","credit",false,"active",0],
      ["2.1.01","Cuentas por Pagar","liability","credit",false,"active",20],
      ["2.1.01.01","Cuentas por Pagar Proveedores","liability","credit",true,"active",16],
      ["2.1.01.02","Otras Cuentas por Pagar","liability","credit",true,"active",0],
      ["2.1.01.03","Tarjetas de Crédito por Pagar","liability","credit",true,"active",15],
      ["2.1.02","Impuestos Retenidos y por Pagar","liability","credit",false,"active",0],
      ["2.1.02.01","ITBIS Cobrado en Ventas","liability","credit",true,"active",36],
      ["2.1.02.02","ITBIS Retenido por Pagar","liability","credit",true,"active",0],
      ["2.1.02.03","Retenciones de ISR por Pagar","liability","credit",true,"active",0],
      ["2.1.03","ITBIS por Pagar","liability","credit",true,"active",43],
      ["2.1.04","ISR Retenido por Pagar","liability","credit",true,"active",1],
      ["2.1.05","ITBIS Retenido por Pagar","liability","credit",true,"active",2],
      ["3","Patrimonio","equity","credit",false,"active",0],
      ["3.1","Capital Social","equity","credit",false,"active",0],
      ["3.1.01","Capital Suscrito y Pagado","equity","credit",true,"active",0],
      ["3.2","Resultados","equity","credit",false,"active",0],
      ["3.2.01","Utilidades Acumuladas","equity","credit",true,"active",0],
      ["4","Ingresos","revenue","credit",false,"active",0],
      ["4.1","Ingresos Operacionales","revenue","credit",false,"active",0],
      ["4.1.01","Ventas de Mercancías","revenue","credit",true,"active",87],
      ["4.1.02","Ventas de Servicios","revenue","credit",true,"active",0],
      ["5","Costos","expense","debit",false,"active",0],
      ["5.1","Costos de Ventas","expense","debit",false,"active",2],
      ["5.1.01","Costo de Ventas Mercancías","expense","debit",true,"active",124],
      ["5.1.02","Otros Impuestos y Tasas","expense","debit",true,"active",3],
      ["6","Gastos","expense","debit",false,"active",0],
      ["6.1","Gastos Operacionales","expense","debit",false,"active",0],
      ["6.1.01","Gastos de Personal","expense","debit",false,"active",0],
      ["6.1.01.01","Sueldos y Salarios","expense","debit",true,"active",0],
      ["6.1.01.02","Retenciones TSS (SFS/AFP/TSS)","expense","debit",true,"active",0],
      ["6.1.02","Gastos Administrativos","expense","debit",false,"active",0],
      ["6.1.02.01","Gastos de Energía Eléctrica","expense","debit",true,"active",0],
      ["6.1.02.02","Gastos de Teléfono e Internet","expense","debit",true,"active",0],
      ["6.1.02.03","Gastos de Combustible y Transporte","expense","debit",true,"active",14],
      ["6.1.02.04","Alquileres / Arrendamientos","expense","debit",true,"active",0],
      ["6.1.02.05","Reparación y Mantenimiento","expense","debit",true,"active",1],
      ["6.1.02.06","Gastos Diversos","expense","debit",true,"active",6],
    ],
    claves: ["accounts_receivable=1.1.02.01","bank=1.1.01.04","cash=1.1.01.01","cost_of_goods_sold=5.1.01","credit_card_payable=2.1.01.03","inventory=1.1.03.01","isr_retention_receivable=1.1.04.02","isr_withholding_payable=2.1.04","itbis_purchases=1.1.04.01","itbis_retention_receivable=1.1.04.03","itbis_sales=2.1.02.01","itbis_withholding_payable=2.1.05","other_retention_receivable=1.1.04.04","purchase_itbis_paid=1.1.08","purchase_other_taxes=5.1.02","sales_revenue=4.1.01","supplier_payable=2.1.01.01"],
  },
  "UltraElec": {
    catalogo: [
      ["1","Activos","asset","debit",false,"active",0],
      ["1.1","Activo Corriente","asset","debit",false,"active",0],
      ["1.1.01","Efectivo en Caja y Bancos","asset","debit",false,"active",0],
      ["1.1.01.01","Caja General","asset","debit",true,"active",0],
      ["1.1.01.02","Banco Popular","asset","debit",true,"active",0],
      ["1.1.01.03","Banco de Reservas","asset","debit",true,"active",0],
      ["1.1.02","Cuentas por Cobrar","asset","debit",false,"active",0],
      ["1.1.02.01","Cuentas por Cobrar Clientes","asset","debit",true,"active",0],
      ["1.1.02.02","Otras Cuentas por Cobrar","asset","debit",true,"active",0],
      ["1.1.03","Inventarios","asset","debit",false,"active",0],
      ["1.1.03.01","Inventario de Mercancía","asset","debit",true,"active",0],
      ["1.1.04","Impuestos Anticipados","asset","debit",false,"active",0],
      ["1.1.04.01","ITBIS Pagado en Compras","asset","debit",true,"active",0],
      ["1.1.04.02","Anticipos de ISR","asset","debit",true,"active",0],
      ["1.1.04.03","ITBIS Retenido por Clientes","asset","debit",true,"active",0],
      ["1.1.04.04","Otras Retenciones por Clientes","asset","debit",true,"active",0],
      ["1.2","Activos Fijos","asset","debit",false,"active",0],
      ["1.2.01","Propiedades, Planta y Equipo","asset","debit",false,"active",0],
      ["1.2.01.01","Equipos de Transporte","asset","debit",true,"active",0],
      ["1.2.01.02","Equipos de Oficina","asset","debit",true,"active",0],
      ["1.2.01.03","Depreciación Acumulada","asset","credit",true,"active",0],
      ["2","Pasivos","liability","credit",false,"active",0],
      ["2.1","Pasivos Corrientes","liability","credit",false,"active",0],
      ["2.1.01","Cuentas por Pagar","liability","credit",false,"active",0],
      ["2.1.01.01","Cuentas por Pagar Proveedores","liability","credit",true,"active",0],
      ["2.1.01.02","Otras Cuentas por Pagar","liability","credit",true,"active",0],
      ["2.1.01.03","Tarjetas de Crédito por Pagar","liability","credit",true,"active",0],
      ["2.1.02","Impuestos Retenidos y por Pagar","liability","credit",false,"active",0],
      ["2.1.02.01","ITBIS Cobrado en Ventas","liability","credit",true,"active",0],
      ["2.1.02.02","ITBIS Retenido por Pagar","liability","credit",true,"active",0],
      ["2.1.02.03","Retenciones de ISR por Pagar","liability","credit",true,"active",0],
      ["3","Patrimonio","equity","credit",false,"active",0],
      ["3.1","Capital Social","equity","credit",false,"active",0],
      ["3.1.01","Capital Suscrito y Pagado","equity","credit",true,"active",0],
      ["3.2","Resultados","equity","credit",false,"active",0],
      ["3.2.01","Utilidades Acumuladas","equity","credit",true,"active",0],
      ["4","Ingresos","revenue","credit",false,"active",0],
      ["4.1","Ingresos Operacionales","revenue","credit",false,"active",0],
      ["4.1.01","Ventas de Mercancías","revenue","credit",true,"active",0],
      ["4.1.02","Ventas de Servicios","revenue","credit",true,"active",0],
      ["5","Costos","expense","debit",false,"active",0],
      ["5.1","Costos de Ventas","expense","debit",false,"active",0],
      ["5.1.01","Costo de Ventas Mercancías","expense","debit",true,"active",0],
      ["5.1.02","Otros Impuestos y Tasas","expense","debit",true,"active",0],
      ["6","Gastos","expense","debit",false,"active",0],
      ["6.1","Gastos Operacionales","expense","debit",false,"active",0],
      ["6.1.01","Gastos de Personal","expense","debit",false,"active",0],
      ["6.1.01.01","Sueldos y Salarios","expense","debit",true,"active",0],
      ["6.1.01.02","Retenciones TSS (SFS/AFP/TSS)","expense","debit",true,"active",0],
      ["6.1.02","Gastos Administrativos","expense","debit",false,"active",0],
      ["6.1.02.01","Gastos de Energía Eléctrica","expense","debit",true,"active",0],
      ["6.1.02.02","Gastos de Teléfono e Internet","expense","debit",true,"active",0],
      ["6.1.02.03","Gastos de Combustible y Transporte","expense","debit",true,"active",0],
      ["6.1.02.04","Alquileres / Arrendamientos","expense","debit",true,"active",0],
      ["6.1.02.05","Reparación y Mantenimiento","expense","debit",true,"active",0],
      ["6.1.02.06","Gastos Diversos","expense","debit",true,"active",0],
    ],
    claves: ["accounts_receivable=1.1.02.01","bank=1.1.01.02","cash=1.1.01.01","cost_of_goods_sold=5.1.01","credit_card_payable=2.1.01.03","inventory=1.1.03.01","isr_retention_receivable=1.1.04.02","isr_withholding_payable=2.1.02.03","itbis_purchases=1.1.04.01","itbis_retention_receivable=1.1.04.03","itbis_sales=2.1.02.01","itbis_withholding_payable=2.1.02.02","other_retention_receivable=1.1.04.04","purchase_itbis_paid=1.1.04.01","purchase_other_taxes=5.1.02","sales_revenue=4.1.01","supplier_payable=2.1.01.01"],
  },
};
