-- estado_migraciones.sql
--
-- QUE ES ESTO
-- -----------
-- `drizzle.__drizzle_migrations` dice que solo se aplicaron las migraciones 0000
-- a 0007. Las demas se han ido aplicando a mano -- los scripts
-- scratch/apply-migration-*.ts lo confirman -- y esas ejecuciones no dejan
-- registro, asi que el ledger no sirve para saber que hay en la base.
--
-- Por eso NO se debe correr `drizzle migrate`: intentaria replicar 23
-- migraciones sobre un esquema que ya tiene casi todo. En el mejor caso falla;
-- en el peor aplica a medias.
--
-- Este fichero no replica nada. Mira el catalogo de PostgreSQL y dice, objeto
-- por objeto, cuales de los 353 que declaran esas migraciones NO existen.
-- Es de SOLO LECTURA.
--
-- Descuenta los objetos que una migracion posterior BORRA: `delivery_notes_num_idx`
-- se crea en la 0011 y la 0026 lo elimina al sustituirlo por la version con
-- `modo`, asi que su ausencia es correcta y no se reporta.
--
-- Si devuelve vacio, el esquema esta completo y lo unico roto es el ledger.
-- Si devuelve filas, esas son las que faltan de verdad. Hay que leerlas antes de
-- aplicarlas: el analisis es textual, y un objeto puede haberse creado con otro
-- nombre o por otra via.
--
-- Devuelve dos resultados: el detalle y un resumen por migracion.

WITH esperado(migracion, tipo, tabla, nombre) AS (
  VALUES
    ('0008_sparkling_bug','tabla','inventory_levels',''),
    ('0008_sparkling_bug','tabla','inventory_movements',''),
    ('0008_sparkling_bug','tabla','inventory_transfer_lines',''),
    ('0008_sparkling_bug','tabla','inventory_transfers',''),
    ('0008_sparkling_bug','tabla','user_warehouses',''),
    ('0008_sparkling_bug','tabla','warehouses',''),
    ('0008_sparkling_bug','columna','expenses','warehouse_id'),
    ('0008_sparkling_bug','columna','invoices','warehouse_id'),
    ('0008_sparkling_bug','restriccion','inventory_levels','inventory_levels_company_id_companies_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_levels','inventory_levels_product_id_products_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_levels','inventory_levels_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_movements','inventory_movements_company_id_companies_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_movements','inventory_movements_product_id_products_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_movements','inventory_movements_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_movements','inventory_movements_user_id_users_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfer_lines','inventory_transfer_lines_transfer_id_inventory_transfers_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfer_lines','inventory_transfer_lines_product_id_products_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfers','inventory_transfers_company_id_companies_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfers','inventory_transfers_source_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfers','inventory_transfers_destination_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfers','inventory_transfers_user_id_users_id_fk'),
    ('0008_sparkling_bug','restriccion','user_warehouses','user_warehouses_company_id_companies_id_fk'),
    ('0008_sparkling_bug','restriccion','user_warehouses','user_warehouses_user_id_users_id_fk'),
    ('0008_sparkling_bug','restriccion','user_warehouses','user_warehouses_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','warehouses','warehouses_company_id_companies_id_fk'),
    ('0008_sparkling_bug','indice','','inventory_levels_company_idx'),
    ('0008_sparkling_bug','indice','','inv_movements_company_idx'),
    ('0008_sparkling_bug','indice','','inv_movements_prod_wh_idx'),
    ('0008_sparkling_bug','indice','','inv_movements_created_idx'),
    ('0008_sparkling_bug','indice','','inv_trans_lines_transfer_idx'),
    ('0008_sparkling_bug','indice','','inv_transfers_company_idx'),
    ('0008_sparkling_bug','indice','','user_warehouses_user_wh_idx'),
    ('0008_sparkling_bug','indice','','user_warehouses_company_idx'),
    ('0008_sparkling_bug','indice','','warehouses_company_idx'),
    ('0008_sparkling_bug','indice','','warehouses_company_code_idx'),
    ('0008_sparkling_bug','restriccion','expenses','expenses_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','invoices','invoices_warehouse_id_warehouses_id_fk'),
    ('0009_known_proemial_gods','tabla','expense_lines',''),
    ('0009_known_proemial_gods','columna','bank_accounts','color'),
    ('0009_known_proemial_gods','columna','expenses','is_minor_expense'),
    ('0009_known_proemial_gods','columna','expenses','description'),
    ('0009_known_proemial_gods','columna','product_categories','description'),
    ('0009_known_proemial_gods','restriccion','expense_lines','expense_lines_expense_id_expenses_id_fk'),
    ('0009_known_proemial_gods','restriccion','expense_lines','expense_lines_product_id_products_id_fk'),
    ('0009_known_proemial_gods','indice','','expense_line_exp_idx'),
    ('0009_known_proemial_gods','indice','','expense_line_prod_idx'),
    ('0010_narrow_tarot','columna','invoices','payment_type'),
    ('0010_narrow_tarot','columna','invoices','bank_name'),
    ('0010_narrow_tarot','columna','invoices','transaction_number'),
    ('0011_add_codigo_factura','tabla','factura_secuencias',''),
    ('0011_add_codigo_factura','columna','invoices','codigo_factura'),
    ('0011_add_codigo_factura','restriccion','invoices','invoices_codigo_factura_unique'),
    ('0011_round_forge','columna','companies','address'),
    ('0011_round_forge','columna','delivery_notes','delivery_number'),
    ('0011_round_forge','columna','delivery_notes','dispatcher_name'),
    ('0011_round_forge','columna','delivery_notes','notes'),
    ('0011_round_forge','columna','delivery_notes','approved_by'),
    ('0011_round_forge','columna','delivery_notes','approved_at'),
    ('0011_round_forge','columna','delivery_notes','voided_by'),
    ('0011_round_forge','columna','delivery_notes','voided_at'),
    ('0011_round_forge','columna','invoices','notes'),
    ('0011_round_forge','columna','invoices','modified_ncf'),
    ('0011_round_forge','columna','invoices','modified_invoice_id'),
    ('0011_round_forge','columna','invoices','delivery_status'),
    ('0011_round_forge','restriccion','delivery_notes','delivery_notes_approved_by_users_id_fk'),
    ('0011_round_forge','restriccion','delivery_notes','delivery_notes_voided_by_users_id_fk'),
    ('0012_ambiguous_texas_twister','tabla','quote_lines',''),
    ('0012_ambiguous_texas_twister','tabla','quote_sequences',''),
    ('0012_ambiguous_texas_twister','tabla','quote_taxes',''),
    ('0012_ambiguous_texas_twister','tabla','quotes',''),
    ('0012_ambiguous_texas_twister','columna','invoices','quote_id'),
    ('0012_ambiguous_texas_twister','restriccion','quote_lines','quote_lines_quote_id_quotes_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quote_lines','quote_lines_product_id_products_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quote_sequences','quote_sequences_company_id_companies_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quote_taxes','quote_taxes_quote_id_quotes_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quotes','quotes_company_id_companies_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quotes','quotes_warehouse_id_warehouses_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quotes','quotes_customer_id_customers_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quotes','quotes_user_id_users_id_fk'),
    ('0012_ambiguous_texas_twister','indice','','quote_lines_quote_idx'),
    ('0012_ambiguous_texas_twister','indice','','quote_taxes_quote_idx'),
    ('0012_ambiguous_texas_twister','indice','','quotes_status_idx'),
    ('0012_ambiguous_texas_twister','restriccion','invoices','invoices_quote_id_quotes_id_fk'),
    ('0013_add_retentions','columna','invoices','total_retained'),
    ('0013_add_retentions','columna','invoices','total_net'),
    ('0013_add_retentions','tabla','retentions',''),
    ('0013_add_retentions','tabla','invoice_retentions',''),
    ('0013_add_retentions','indice','','invoice_retentions_invoice_idx'),
    ('0013_add_retentions','restriccion','retentions','retentions_company_id_companies_id_fk'),
    ('0013_add_retentions','restriccion','invoice_retentions','invoice_retentions_invoice_id_invoices_id_fk'),
    ('0013_add_retentions','restriccion','invoice_retentions','invoice_retentions_retention_id_retentions_id_fk'),
    ('0013_add_retentions','restriccion','invoice_retentions','invoice_retentions_created_by_users_id_fk'),
    ('0013_next_gauntlet','columna','companies','email'),
    ('0014_spotty_king_bedlam','tabla','departments',''),
    ('0014_spotty_king_bedlam','tabla','employee_deductions',''),
    ('0014_spotty_king_bedlam','tabla','employee_income',''),
    ('0014_spotty_king_bedlam','tabla','employee_leaves',''),
    ('0014_spotty_king_bedlam','tabla','employee_settlements',''),
    ('0014_spotty_king_bedlam','tabla','employee_vacations',''),
    ('0014_spotty_king_bedlam','tabla','employees',''),
    ('0014_spotty_king_bedlam','tabla','isr_brackets',''),
    ('0014_spotty_king_bedlam','tabla','overtime_records',''),
    ('0014_spotty_king_bedlam','tabla','payroll_configs',''),
    ('0014_spotty_king_bedlam','tabla','payroll_details',''),
    ('0014_spotty_king_bedlam','tabla','payrolls',''),
    ('0014_spotty_king_bedlam','tabla','positions',''),
    ('0014_spotty_king_bedlam','restriccion','departments','departments_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_deductions','employee_deductions_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_deductions','employee_deductions_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_income','employee_income_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_income','employee_income_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_leaves','employee_leaves_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_leaves','employee_leaves_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_settlements','employee_settlements_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_settlements','employee_settlements_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_vacations','employee_vacations_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_vacations','employee_vacations_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employees','employees_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employees','employees_department_id_departments_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employees','employees_position_id_positions_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','overtime_records','overtime_records_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','overtime_records','overtime_records_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payroll_configs','payroll_configs_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payroll_details','payroll_details_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payroll_details','payroll_details_payroll_id_payrolls_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payroll_details','payroll_details_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payrolls','payrolls_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payrolls','payrolls_created_by_users_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','positions','positions_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','indice','','departments_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_deductions_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_deductions_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_income_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_income_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_leaves_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_leaves_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_settlements_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_settlements_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_vacations_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employees_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employees_code_idx'),
    ('0014_spotty_king_bedlam','indice','','employees_cedula_idx'),
    ('0014_spotty_king_bedlam','indice','','overtime_records_company_idx'),
    ('0014_spotty_king_bedlam','indice','','overtime_records_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','payroll_configs_company_idx'),
    ('0014_spotty_king_bedlam','indice','','payroll_details_company_idx'),
    ('0014_spotty_king_bedlam','indice','','payroll_details_payroll_idx'),
    ('0014_spotty_king_bedlam','indice','','payroll_details_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','payrolls_company_idx'),
    ('0014_spotty_king_bedlam','indice','','positions_company_idx'),
    ('0015_add_indicador_nota_credito','columna','invoices','indicador_nota_credito'),
    ('0015_premium_boomer','indice','','expense_comp_issue_date_idx'),
    ('0015_premium_boomer','indice','','journal_entries_comp_status_date_idx'),
    ('0015_premium_boomer','indice','','journal_entry_lines_comp_acc_idx'),
    ('0016_handy_klaw','tabla','plans',''),
    ('0016_handy_klaw','tabla','subscriptions',''),
    ('0016_handy_klaw','restriccion','subscriptions','subscriptions_company_id_companies_id_fk'),
    ('0016_handy_klaw','restriccion','subscriptions','subscriptions_plan_id_plans_id_fk'),
    ('0016_handy_klaw','indice','','subscriptions_company_idx'),
    ('0017_breezy_wolfpack','indice','','retentions_company_active_idx'),
    ('0017_breezy_wolfpack','indice','','journal_entry_lines_acc_created_idx'),
    ('0018_flashy_thor_girl','tabla','accounting_mappings',''),
    ('0018_flashy_thor_girl','tabla','accounting_periods',''),
    ('0018_flashy_thor_girl','columna','chart_of_accounts','nature'),
    ('0018_flashy_thor_girl','columna','chart_of_accounts','level'),
    ('0018_flashy_thor_girl','columna','chart_of_accounts','is_transactional'),
    ('0018_flashy_thor_girl','restriccion','accounting_mappings','accounting_mappings_company_id_companies_id_fk'),
    ('0018_flashy_thor_girl','restriccion','accounting_mappings','accounting_mappings_account_id_chart_of_accounts_id_fk'),
    ('0018_flashy_thor_girl','restriccion','accounting_periods','accounting_periods_company_id_companies_id_fk'),
    ('0018_flashy_thor_girl','indice','','accounting_mappings_company_key_idx'),
    ('0018_flashy_thor_girl','indice','','accounting_periods_company_idx'),
    ('0018_flashy_thor_girl','indice','','accounting_periods_status_idx'),
    ('0019_add_user_avatar_fields','columna','users','avatar_url'),
    ('0019_add_user_avatar_fields','columna','users','avatar_path'),
    ('0020_add_rbac_system_tables','tabla','audit_permissions',''),
    ('0020_add_rbac_system_tables','tabla','route_mappings',''),
    ('0020_add_rbac_system_tables','restriccion','audit_permissions','audit_permissions_company_id_companies_id_fk'),
    ('0020_add_rbac_system_tables','restriccion','audit_permissions','audit_permissions_user_id_users_id_fk'),
    ('0020_add_rbac_system_tables','indice','','audit_permissions_company_idx'),
    ('0020_add_rbac_system_tables','indice','','audit_permissions_user_idx'),
    ('0020_add_rbac_system_tables','indice','','audit_permissions_created_idx'),
    ('0020_add_rbac_system_tables','indice','','route_mappings_pattern_idx'),
    ('0022_dapper_skreet','tabla','financial_movements',''),
    ('0022_dapper_skreet','columna','employees','payment_frequency'),
    ('0022_dapper_skreet','columna','payrolls','frequency'),
    ('0022_dapper_skreet','restriccion','financial_movements','financial_movements_company_id_companies_id_fk'),
    ('0022_dapper_skreet','restriccion','financial_movements','financial_movements_customer_id_customers_id_fk'),
    ('0022_dapper_skreet','restriccion','financial_movements','financial_movements_supplier_id_suppliers_id_fk'),
    ('0022_dapper_skreet','restriccion','financial_movements','financial_movements_user_id_users_id_fk'),
    ('0022_dapper_skreet','indice','','fin_mov_company_idx'),
    ('0022_dapper_skreet','indice','','fin_mov_customer_idx'),
    ('0022_dapper_skreet','indice','','fin_mov_supplier_idx'),
    ('0022_dapper_skreet','indice','','fin_mov_date_idx'),
    ('0022_dapper_skreet','indice','','fin_mov_created_at_idx'),
    ('0023_right_silver_samurai','columna','customers','credit_limit'),
    ('0024_petite_blizzard','columna','invoice_lines','warehouse_id'),
    ('0024_petite_blizzard','restriccion','invoice_lines','invoice_lines_warehouse_id_warehouses_id_fk'),
    ('0025_wide_cassandra_nova','columna','company_settings','print_copies'),
    ('0025_wide_cassandra_nova','columna','invoices','mseller_xml_path'),
    ('0026_glorious_serpent_society','tipo','environment_mode',''),
    ('0026_glorious_serpent_society','columna','inventory_levels','modo'),
    ('0026_glorious_serpent_society','columna','inventory_movements','modo'),
    ('0026_glorious_serpent_society','columna','inventory_transfers','modo'),
    ('0026_glorious_serpent_society','columna','cash_movements','modo'),
    ('0026_glorious_serpent_society','columna','cash_session_summary','modo'),
    ('0026_glorious_serpent_society','columna','cash_sessions','modo'),
    ('0026_glorious_serpent_society','columna','credit_debit_notes','modo'),
    ('0026_glorious_serpent_society','columna','delivery_notes','modo'),
    ('0026_glorious_serpent_society','columna','dgii_submissions','modo'),
    ('0026_glorious_serpent_society','columna','ecf_sequences','modo'),
    ('0026_glorious_serpent_society','columna','invoices','modo'),
    ('0026_glorious_serpent_society','columna','quote_sequences','modo'),
    ('0026_glorious_serpent_society','columna','quotes','modo'),
    ('0026_glorious_serpent_society','columna','bank_reconciliations','modo'),
    ('0026_glorious_serpent_society','columna','bank_transactions','modo'),
    ('0026_glorious_serpent_society','columna','accounting_periods','modo'),
    ('0026_glorious_serpent_society','columna','accounts_payable','modo'),
    ('0026_glorious_serpent_society','columna','accounts_receivable','modo'),
    ('0026_glorious_serpent_society','columna','ap_payments','modo'),
    ('0026_glorious_serpent_society','columna','checks','modo'),
    ('0026_glorious_serpent_society','columna','customer_receipts','modo'),
    ('0026_glorious_serpent_society','columna','expenses','modo'),
    ('0026_glorious_serpent_society','columna','financial_movements','modo'),
    ('0026_glorious_serpent_society','columna','journal_entries','modo'),
    ('0026_glorious_serpent_society','columna','journal_entry_lines','modo'),
    ('0026_glorious_serpent_society','columna','supplier_payments','modo'),
    ('0026_glorious_serpent_society','columna','audit_logs','modo'),
    ('0026_glorious_serpent_society','columna','audit_logs','user_agent'),
    ('0026_glorious_serpent_society','columna','employee_deductions','modo'),
    ('0026_glorious_serpent_society','columna','employee_income','modo'),
    ('0026_glorious_serpent_society','columna','employee_leaves','modo'),
    ('0026_glorious_serpent_society','columna','employee_settlements','modo'),
    ('0026_glorious_serpent_society','columna','employee_vacations','modo'),
    ('0026_glorious_serpent_society','columna','overtime_records','modo'),
    ('0026_glorious_serpent_society','columna','payroll_details','modo'),
    ('0026_glorious_serpent_society','columna','payrolls','modo'),
    ('0026_glorious_serpent_society','indice','','inventory_levels_prod_wh_modo_idx'),
    ('0026_glorious_serpent_society','indice','','inventory_levels_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','inv_movements_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','inv_transfers_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','cash_movements_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','cash_session_summary_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','cash_sessions_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','credit_debit_notes_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','delivery_notes_num_modo_idx'),
    ('0026_glorious_serpent_society','indice','','dgii_submissions_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','ecf_seq_company_type_modo_idx'),
    ('0026_glorious_serpent_society','indice','','invoices_company_ncf_modo_idx'),
    ('0026_glorious_serpent_society','indice','','invoices_codigo_factura_modo_idx'),
    ('0026_glorious_serpent_society','indice','','invoices_comp_status_created_modo_idx'),
    ('0026_glorious_serpent_society','indice','','quote_seq_company_year_modo_idx'),
    ('0026_glorious_serpent_society','indice','','quotes_company_seq_modo_idx'),
    ('0026_glorious_serpent_society','indice','','bank_recon_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','bank_txs_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','accounting_periods_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','ap_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','ar_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','ap_payments_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','checks_company_num_modo_idx'),
    ('0026_glorious_serpent_society','indice','','cust_receipts_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','expense_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','fin_mov_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','journal_entries_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','journal_entry_lines_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','supp_pay_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','audit_logs_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_deductions_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_income_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_leaves_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_settlements_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_vacations_employee_modo_idx'),
    ('0026_glorious_serpent_society','indice','','overtime_records_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','payroll_details_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','payrolls_company_modo_idx'),
    ('0027_faulty_lake','tabla','barcode_print_logs',''),
    ('0027_faulty_lake','tabla','product_barcodes',''),
    ('0027_faulty_lake','columna','company_settings','barcode_default_type'),
    ('0027_faulty_lake','columna','company_settings','barcode_prefix'),
    ('0027_faulty_lake','columna','company_settings','barcode_length'),
    ('0027_faulty_lake','restriccion','barcode_print_logs','barcode_print_logs_company_id_companies_id_fk'),
    ('0027_faulty_lake','restriccion','barcode_print_logs','barcode_print_logs_product_id_products_id_fk'),
    ('0027_faulty_lake','restriccion','barcode_print_logs','barcode_print_logs_user_id_users_id_fk'),
    ('0027_faulty_lake','restriccion','product_barcodes','product_barcodes_company_id_companies_id_fk'),
    ('0027_faulty_lake','restriccion','product_barcodes','product_barcodes_product_id_products_id_fk'),
    ('0027_faulty_lake','indice','','barcode_print_logs_company_idx'),
    ('0027_faulty_lake','indice','','barcode_print_logs_product_idx'),
    ('0027_faulty_lake','indice','','prod_barcodes_company_idx'),
    ('0027_faulty_lake','indice','','prod_barcodes_product_idx'),
    ('0027_faulty_lake','indice','','prod_barcodes_barcode_idx'),
    ('0028_foamy_iron_fist','tabla','supplier_order_lines',''),
    ('0028_foamy_iron_fist','tabla','supplier_order_sequences',''),
    ('0028_foamy_iron_fist','tabla','supplier_orders',''),
    ('0028_foamy_iron_fist','restriccion','supplier_order_lines','supplier_order_lines_order_id_supplier_orders_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_order_lines','supplier_order_lines_product_id_products_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_order_sequences','supplier_order_sequences_company_id_companies_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_orders','supplier_orders_company_id_companies_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_orders','supplier_orders_supplier_id_suppliers_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_orders','supplier_orders_user_id_users_id_fk'),
    ('0028_foamy_iron_fist','indice','','supplier_order_lines_order_idx'),
    ('0028_foamy_iron_fist','indice','','supplier_order_seq_company_year_modo_idx'),
    ('0028_foamy_iron_fist','indice','','supplier_orders_company_num_modo_idx'),
    ('0028_foamy_iron_fist','indice','','supplier_orders_status_idx'),
    ('0028_foamy_iron_fist','indice','','supplier_orders_supplier_idx'),
    ('0029_add_checks_cleared_date','columna','checks','cleared_date'),
    ('0029_add_checks_cleared_date','indice','','checks_cleared_date_idx'),
    ('0030_reconciliacion','tabla','expense_types',''),
    ('0030_reconciliacion','tabla','agent_proposals',''),
    ('0030_reconciliacion','tabla','document_shares',''),
    ('0030_reconciliacion','tabla','system_email_logs',''),
    ('0030_reconciliacion','tabla','purchase_orders',''),
    ('0030_reconciliacion','tabla','purchase_order_items',''),
    ('0030_reconciliacion','tabla','purchase_order_logs',''),
    ('0030_reconciliacion','columna','accounts_payable','expense_id'),
    ('0030_reconciliacion','columna','accounts_payable','purchase_order_id'),
    ('0030_reconciliacion','columna','companies','phone'),
    ('0030_reconciliacion','columna','customers','price_type'),
    ('0030_reconciliacion','columna','products','is_on_sale'),
    ('0030_reconciliacion','columna','products','promotional_price'),
    ('0030_reconciliacion','columna','route_mappings','is_menu_item'),
    ('0030_reconciliacion','columna','route_mappings','display_name'),
    ('0030_reconciliacion','columna','route_mappings','group_name'),
    ('0030_reconciliacion','columna','route_mappings','icon_name'),
    ('0030_reconciliacion','columna','route_mappings','order_index'),
    ('0030_reconciliacion','restriccion','accounts_payable','accounts_payable_purchase_order_id_purchase_orders_id_fk'),
    ('0030_reconciliacion','restriccion','expense_types','expense_types_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','system_email_logs','system_email_logs_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','system_email_logs','system_email_logs_user_id_users_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_order_items','purchase_order_items_purchase_order_id_purchase_orders_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_order_items','purchase_order_items_product_id_products_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_order_logs','purchase_order_logs_purchase_order_id_purchase_orders_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_order_logs','purchase_order_logs_user_id_users_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_orders','purchase_orders_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_orders','purchase_orders_supplier_id_suppliers_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_orders','purchase_orders_warehouse_id_warehouses_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_orders','purchase_orders_created_by_users_id_fk'),
    ('0030_reconciliacion','restriccion','agent_proposals','agent_proposals_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','agent_proposals','agent_proposals_user_id_users_id_fk'),
    ('0030_reconciliacion','restriccion','document_shares','document_shares_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','document_shares','document_shares_created_by_users_id_fk'),
    ('0030_reconciliacion','restriccion','accounts_payable','accounts_payable_expense_id_expenses_id_fk'),
    ('0030_reconciliacion','indice','','expense_types_company_code_idx'),
    ('0030_reconciliacion','indice','','expense_types_company_idx'),
    ('0030_reconciliacion','indice','','system_email_logs_company_idx'),
    ('0030_reconciliacion','indice','','system_email_logs_context_idx'),
    ('0030_reconciliacion','indice','','system_email_logs_status_idx'),
    ('0030_reconciliacion','indice','','purchase_order_items_order_idx'),
    ('0030_reconciliacion','indice','','purchase_order_logs_order_idx'),
    ('0030_reconciliacion','indice','','purchase_orders_company_num_modo_idx'),
    ('0030_reconciliacion','indice','','purchase_orders_status_idx'),
    ('0030_reconciliacion','indice','','purchase_orders_supplier_idx'),
    ('0030_reconciliacion','indice','','agent_proposals_company_modo_idx'),
    ('0030_reconciliacion','indice','','agent_proposals_area_idx'),
    ('0031_inventario_no_negativo','restriccion','inventory_levels','chk_inventory_no_negativo')
),
existente AS (
  SELECT 'tabla' AS tipo, table_name::text AS tabla, '' AS nombre
  FROM information_schema.tables WHERE table_schema = 'public'
  UNION ALL
  SELECT 'columna', table_name::text, column_name::text
  FROM information_schema.columns WHERE table_schema = 'public'
  UNION ALL
  SELECT 'restriccion', rel.relname::text, con.conname::text
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = rel.relnamespace AND n.nspname = 'public'
  UNION ALL
  SELECT 'indice', '', indexname::text
  FROM pg_indexes WHERE schemaname = 'public'
  UNION ALL
  SELECT 'tipo', typname::text, ''
  FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace AND n.nspname = 'public'
)
SELECT e.migracion, e.tipo, e.tabla, e.nombre
FROM esperado e
WHERE NOT EXISTS (
  SELECT 1 FROM existente r
  WHERE r.tipo = e.tipo
    AND lower(r.tabla) = lower(e.tabla)
    AND lower(r.nombre) = lower(e.nombre)
)
ORDER BY e.migracion, e.tipo, e.tabla, e.nombre;

-- ---------------------------------------------------------------------------
-- Resumen: cuantos objetos faltan de cada migracion.
-- ---------------------------------------------------------------------------
WITH esperado(migracion, tipo, tabla, nombre) AS (
  VALUES
    ('0008_sparkling_bug','tabla','inventory_levels',''),
    ('0008_sparkling_bug','tabla','inventory_movements',''),
    ('0008_sparkling_bug','tabla','inventory_transfer_lines',''),
    ('0008_sparkling_bug','tabla','inventory_transfers',''),
    ('0008_sparkling_bug','tabla','user_warehouses',''),
    ('0008_sparkling_bug','tabla','warehouses',''),
    ('0008_sparkling_bug','columna','expenses','warehouse_id'),
    ('0008_sparkling_bug','columna','invoices','warehouse_id'),
    ('0008_sparkling_bug','restriccion','inventory_levels','inventory_levels_company_id_companies_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_levels','inventory_levels_product_id_products_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_levels','inventory_levels_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_movements','inventory_movements_company_id_companies_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_movements','inventory_movements_product_id_products_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_movements','inventory_movements_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_movements','inventory_movements_user_id_users_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfer_lines','inventory_transfer_lines_transfer_id_inventory_transfers_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfer_lines','inventory_transfer_lines_product_id_products_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfers','inventory_transfers_company_id_companies_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfers','inventory_transfers_source_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfers','inventory_transfers_destination_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','inventory_transfers','inventory_transfers_user_id_users_id_fk'),
    ('0008_sparkling_bug','restriccion','user_warehouses','user_warehouses_company_id_companies_id_fk'),
    ('0008_sparkling_bug','restriccion','user_warehouses','user_warehouses_user_id_users_id_fk'),
    ('0008_sparkling_bug','restriccion','user_warehouses','user_warehouses_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','warehouses','warehouses_company_id_companies_id_fk'),
    ('0008_sparkling_bug','indice','','inventory_levels_company_idx'),
    ('0008_sparkling_bug','indice','','inv_movements_company_idx'),
    ('0008_sparkling_bug','indice','','inv_movements_prod_wh_idx'),
    ('0008_sparkling_bug','indice','','inv_movements_created_idx'),
    ('0008_sparkling_bug','indice','','inv_trans_lines_transfer_idx'),
    ('0008_sparkling_bug','indice','','inv_transfers_company_idx'),
    ('0008_sparkling_bug','indice','','user_warehouses_user_wh_idx'),
    ('0008_sparkling_bug','indice','','user_warehouses_company_idx'),
    ('0008_sparkling_bug','indice','','warehouses_company_idx'),
    ('0008_sparkling_bug','indice','','warehouses_company_code_idx'),
    ('0008_sparkling_bug','restriccion','expenses','expenses_warehouse_id_warehouses_id_fk'),
    ('0008_sparkling_bug','restriccion','invoices','invoices_warehouse_id_warehouses_id_fk'),
    ('0009_known_proemial_gods','tabla','expense_lines',''),
    ('0009_known_proemial_gods','columna','bank_accounts','color'),
    ('0009_known_proemial_gods','columna','expenses','is_minor_expense'),
    ('0009_known_proemial_gods','columna','expenses','description'),
    ('0009_known_proemial_gods','columna','product_categories','description'),
    ('0009_known_proemial_gods','restriccion','expense_lines','expense_lines_expense_id_expenses_id_fk'),
    ('0009_known_proemial_gods','restriccion','expense_lines','expense_lines_product_id_products_id_fk'),
    ('0009_known_proemial_gods','indice','','expense_line_exp_idx'),
    ('0009_known_proemial_gods','indice','','expense_line_prod_idx'),
    ('0010_narrow_tarot','columna','invoices','payment_type'),
    ('0010_narrow_tarot','columna','invoices','bank_name'),
    ('0010_narrow_tarot','columna','invoices','transaction_number'),
    ('0011_add_codigo_factura','tabla','factura_secuencias',''),
    ('0011_add_codigo_factura','columna','invoices','codigo_factura'),
    ('0011_add_codigo_factura','restriccion','invoices','invoices_codigo_factura_unique'),
    ('0011_round_forge','columna','companies','address'),
    ('0011_round_forge','columna','delivery_notes','delivery_number'),
    ('0011_round_forge','columna','delivery_notes','dispatcher_name'),
    ('0011_round_forge','columna','delivery_notes','notes'),
    ('0011_round_forge','columna','delivery_notes','approved_by'),
    ('0011_round_forge','columna','delivery_notes','approved_at'),
    ('0011_round_forge','columna','delivery_notes','voided_by'),
    ('0011_round_forge','columna','delivery_notes','voided_at'),
    ('0011_round_forge','columna','invoices','notes'),
    ('0011_round_forge','columna','invoices','modified_ncf'),
    ('0011_round_forge','columna','invoices','modified_invoice_id'),
    ('0011_round_forge','columna','invoices','delivery_status'),
    ('0011_round_forge','restriccion','delivery_notes','delivery_notes_approved_by_users_id_fk'),
    ('0011_round_forge','restriccion','delivery_notes','delivery_notes_voided_by_users_id_fk'),
    ('0012_ambiguous_texas_twister','tabla','quote_lines',''),
    ('0012_ambiguous_texas_twister','tabla','quote_sequences',''),
    ('0012_ambiguous_texas_twister','tabla','quote_taxes',''),
    ('0012_ambiguous_texas_twister','tabla','quotes',''),
    ('0012_ambiguous_texas_twister','columna','invoices','quote_id'),
    ('0012_ambiguous_texas_twister','restriccion','quote_lines','quote_lines_quote_id_quotes_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quote_lines','quote_lines_product_id_products_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quote_sequences','quote_sequences_company_id_companies_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quote_taxes','quote_taxes_quote_id_quotes_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quotes','quotes_company_id_companies_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quotes','quotes_warehouse_id_warehouses_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quotes','quotes_customer_id_customers_id_fk'),
    ('0012_ambiguous_texas_twister','restriccion','quotes','quotes_user_id_users_id_fk'),
    ('0012_ambiguous_texas_twister','indice','','quote_lines_quote_idx'),
    ('0012_ambiguous_texas_twister','indice','','quote_taxes_quote_idx'),
    ('0012_ambiguous_texas_twister','indice','','quotes_status_idx'),
    ('0012_ambiguous_texas_twister','restriccion','invoices','invoices_quote_id_quotes_id_fk'),
    ('0013_add_retentions','columna','invoices','total_retained'),
    ('0013_add_retentions','columna','invoices','total_net'),
    ('0013_add_retentions','tabla','retentions',''),
    ('0013_add_retentions','tabla','invoice_retentions',''),
    ('0013_add_retentions','indice','','invoice_retentions_invoice_idx'),
    ('0013_add_retentions','restriccion','retentions','retentions_company_id_companies_id_fk'),
    ('0013_add_retentions','restriccion','invoice_retentions','invoice_retentions_invoice_id_invoices_id_fk'),
    ('0013_add_retentions','restriccion','invoice_retentions','invoice_retentions_retention_id_retentions_id_fk'),
    ('0013_add_retentions','restriccion','invoice_retentions','invoice_retentions_created_by_users_id_fk'),
    ('0013_next_gauntlet','columna','companies','email'),
    ('0014_spotty_king_bedlam','tabla','departments',''),
    ('0014_spotty_king_bedlam','tabla','employee_deductions',''),
    ('0014_spotty_king_bedlam','tabla','employee_income',''),
    ('0014_spotty_king_bedlam','tabla','employee_leaves',''),
    ('0014_spotty_king_bedlam','tabla','employee_settlements',''),
    ('0014_spotty_king_bedlam','tabla','employee_vacations',''),
    ('0014_spotty_king_bedlam','tabla','employees',''),
    ('0014_spotty_king_bedlam','tabla','isr_brackets',''),
    ('0014_spotty_king_bedlam','tabla','overtime_records',''),
    ('0014_spotty_king_bedlam','tabla','payroll_configs',''),
    ('0014_spotty_king_bedlam','tabla','payroll_details',''),
    ('0014_spotty_king_bedlam','tabla','payrolls',''),
    ('0014_spotty_king_bedlam','tabla','positions',''),
    ('0014_spotty_king_bedlam','restriccion','departments','departments_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_deductions','employee_deductions_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_deductions','employee_deductions_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_income','employee_income_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_income','employee_income_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_leaves','employee_leaves_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_leaves','employee_leaves_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_settlements','employee_settlements_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_settlements','employee_settlements_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_vacations','employee_vacations_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employee_vacations','employee_vacations_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employees','employees_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employees','employees_department_id_departments_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','employees','employees_position_id_positions_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','overtime_records','overtime_records_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','overtime_records','overtime_records_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payroll_configs','payroll_configs_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payroll_details','payroll_details_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payroll_details','payroll_details_payroll_id_payrolls_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payroll_details','payroll_details_employee_id_employees_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payrolls','payrolls_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','payrolls','payrolls_created_by_users_id_fk'),
    ('0014_spotty_king_bedlam','restriccion','positions','positions_company_id_companies_id_fk'),
    ('0014_spotty_king_bedlam','indice','','departments_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_deductions_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_deductions_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_income_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_income_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_leaves_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_leaves_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_settlements_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_settlements_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','employee_vacations_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employees_company_idx'),
    ('0014_spotty_king_bedlam','indice','','employees_code_idx'),
    ('0014_spotty_king_bedlam','indice','','employees_cedula_idx'),
    ('0014_spotty_king_bedlam','indice','','overtime_records_company_idx'),
    ('0014_spotty_king_bedlam','indice','','overtime_records_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','payroll_configs_company_idx'),
    ('0014_spotty_king_bedlam','indice','','payroll_details_company_idx'),
    ('0014_spotty_king_bedlam','indice','','payroll_details_payroll_idx'),
    ('0014_spotty_king_bedlam','indice','','payroll_details_employee_idx'),
    ('0014_spotty_king_bedlam','indice','','payrolls_company_idx'),
    ('0014_spotty_king_bedlam','indice','','positions_company_idx'),
    ('0015_add_indicador_nota_credito','columna','invoices','indicador_nota_credito'),
    ('0015_premium_boomer','indice','','expense_comp_issue_date_idx'),
    ('0015_premium_boomer','indice','','journal_entries_comp_status_date_idx'),
    ('0015_premium_boomer','indice','','journal_entry_lines_comp_acc_idx'),
    ('0016_handy_klaw','tabla','plans',''),
    ('0016_handy_klaw','tabla','subscriptions',''),
    ('0016_handy_klaw','restriccion','subscriptions','subscriptions_company_id_companies_id_fk'),
    ('0016_handy_klaw','restriccion','subscriptions','subscriptions_plan_id_plans_id_fk'),
    ('0016_handy_klaw','indice','','subscriptions_company_idx'),
    ('0017_breezy_wolfpack','indice','','retentions_company_active_idx'),
    ('0017_breezy_wolfpack','indice','','journal_entry_lines_acc_created_idx'),
    ('0018_flashy_thor_girl','tabla','accounting_mappings',''),
    ('0018_flashy_thor_girl','tabla','accounting_periods',''),
    ('0018_flashy_thor_girl','columna','chart_of_accounts','nature'),
    ('0018_flashy_thor_girl','columna','chart_of_accounts','level'),
    ('0018_flashy_thor_girl','columna','chart_of_accounts','is_transactional'),
    ('0018_flashy_thor_girl','restriccion','accounting_mappings','accounting_mappings_company_id_companies_id_fk'),
    ('0018_flashy_thor_girl','restriccion','accounting_mappings','accounting_mappings_account_id_chart_of_accounts_id_fk'),
    ('0018_flashy_thor_girl','restriccion','accounting_periods','accounting_periods_company_id_companies_id_fk'),
    ('0018_flashy_thor_girl','indice','','accounting_mappings_company_key_idx'),
    ('0018_flashy_thor_girl','indice','','accounting_periods_company_idx'),
    ('0018_flashy_thor_girl','indice','','accounting_periods_status_idx'),
    ('0019_add_user_avatar_fields','columna','users','avatar_url'),
    ('0019_add_user_avatar_fields','columna','users','avatar_path'),
    ('0020_add_rbac_system_tables','tabla','audit_permissions',''),
    ('0020_add_rbac_system_tables','tabla','route_mappings',''),
    ('0020_add_rbac_system_tables','restriccion','audit_permissions','audit_permissions_company_id_companies_id_fk'),
    ('0020_add_rbac_system_tables','restriccion','audit_permissions','audit_permissions_user_id_users_id_fk'),
    ('0020_add_rbac_system_tables','indice','','audit_permissions_company_idx'),
    ('0020_add_rbac_system_tables','indice','','audit_permissions_user_idx'),
    ('0020_add_rbac_system_tables','indice','','audit_permissions_created_idx'),
    ('0020_add_rbac_system_tables','indice','','route_mappings_pattern_idx'),
    ('0022_dapper_skreet','tabla','financial_movements',''),
    ('0022_dapper_skreet','columna','employees','payment_frequency'),
    ('0022_dapper_skreet','columna','payrolls','frequency'),
    ('0022_dapper_skreet','restriccion','financial_movements','financial_movements_company_id_companies_id_fk'),
    ('0022_dapper_skreet','restriccion','financial_movements','financial_movements_customer_id_customers_id_fk'),
    ('0022_dapper_skreet','restriccion','financial_movements','financial_movements_supplier_id_suppliers_id_fk'),
    ('0022_dapper_skreet','restriccion','financial_movements','financial_movements_user_id_users_id_fk'),
    ('0022_dapper_skreet','indice','','fin_mov_company_idx'),
    ('0022_dapper_skreet','indice','','fin_mov_customer_idx'),
    ('0022_dapper_skreet','indice','','fin_mov_supplier_idx'),
    ('0022_dapper_skreet','indice','','fin_mov_date_idx'),
    ('0022_dapper_skreet','indice','','fin_mov_created_at_idx'),
    ('0023_right_silver_samurai','columna','customers','credit_limit'),
    ('0024_petite_blizzard','columna','invoice_lines','warehouse_id'),
    ('0024_petite_blizzard','restriccion','invoice_lines','invoice_lines_warehouse_id_warehouses_id_fk'),
    ('0025_wide_cassandra_nova','columna','company_settings','print_copies'),
    ('0025_wide_cassandra_nova','columna','invoices','mseller_xml_path'),
    ('0026_glorious_serpent_society','tipo','environment_mode',''),
    ('0026_glorious_serpent_society','columna','inventory_levels','modo'),
    ('0026_glorious_serpent_society','columna','inventory_movements','modo'),
    ('0026_glorious_serpent_society','columna','inventory_transfers','modo'),
    ('0026_glorious_serpent_society','columna','cash_movements','modo'),
    ('0026_glorious_serpent_society','columna','cash_session_summary','modo'),
    ('0026_glorious_serpent_society','columna','cash_sessions','modo'),
    ('0026_glorious_serpent_society','columna','credit_debit_notes','modo'),
    ('0026_glorious_serpent_society','columna','delivery_notes','modo'),
    ('0026_glorious_serpent_society','columna','dgii_submissions','modo'),
    ('0026_glorious_serpent_society','columna','ecf_sequences','modo'),
    ('0026_glorious_serpent_society','columna','invoices','modo'),
    ('0026_glorious_serpent_society','columna','quote_sequences','modo'),
    ('0026_glorious_serpent_society','columna','quotes','modo'),
    ('0026_glorious_serpent_society','columna','bank_reconciliations','modo'),
    ('0026_glorious_serpent_society','columna','bank_transactions','modo'),
    ('0026_glorious_serpent_society','columna','accounting_periods','modo'),
    ('0026_glorious_serpent_society','columna','accounts_payable','modo'),
    ('0026_glorious_serpent_society','columna','accounts_receivable','modo'),
    ('0026_glorious_serpent_society','columna','ap_payments','modo'),
    ('0026_glorious_serpent_society','columna','checks','modo'),
    ('0026_glorious_serpent_society','columna','customer_receipts','modo'),
    ('0026_glorious_serpent_society','columna','expenses','modo'),
    ('0026_glorious_serpent_society','columna','financial_movements','modo'),
    ('0026_glorious_serpent_society','columna','journal_entries','modo'),
    ('0026_glorious_serpent_society','columna','journal_entry_lines','modo'),
    ('0026_glorious_serpent_society','columna','supplier_payments','modo'),
    ('0026_glorious_serpent_society','columna','audit_logs','modo'),
    ('0026_glorious_serpent_society','columna','audit_logs','user_agent'),
    ('0026_glorious_serpent_society','columna','employee_deductions','modo'),
    ('0026_glorious_serpent_society','columna','employee_income','modo'),
    ('0026_glorious_serpent_society','columna','employee_leaves','modo'),
    ('0026_glorious_serpent_society','columna','employee_settlements','modo'),
    ('0026_glorious_serpent_society','columna','employee_vacations','modo'),
    ('0026_glorious_serpent_society','columna','overtime_records','modo'),
    ('0026_glorious_serpent_society','columna','payroll_details','modo'),
    ('0026_glorious_serpent_society','columna','payrolls','modo'),
    ('0026_glorious_serpent_society','indice','','inventory_levels_prod_wh_modo_idx'),
    ('0026_glorious_serpent_society','indice','','inventory_levels_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','inv_movements_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','inv_transfers_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','cash_movements_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','cash_session_summary_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','cash_sessions_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','credit_debit_notes_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','delivery_notes_num_modo_idx'),
    ('0026_glorious_serpent_society','indice','','dgii_submissions_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','ecf_seq_company_type_modo_idx'),
    ('0026_glorious_serpent_society','indice','','invoices_company_ncf_modo_idx'),
    ('0026_glorious_serpent_society','indice','','invoices_codigo_factura_modo_idx'),
    ('0026_glorious_serpent_society','indice','','invoices_comp_status_created_modo_idx'),
    ('0026_glorious_serpent_society','indice','','quote_seq_company_year_modo_idx'),
    ('0026_glorious_serpent_society','indice','','quotes_company_seq_modo_idx'),
    ('0026_glorious_serpent_society','indice','','bank_recon_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','bank_txs_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','accounting_periods_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','ap_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','ar_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','ap_payments_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','checks_company_num_modo_idx'),
    ('0026_glorious_serpent_society','indice','','cust_receipts_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','expense_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','fin_mov_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','journal_entries_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','journal_entry_lines_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','supp_pay_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','audit_logs_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_deductions_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_income_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_leaves_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_settlements_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','employee_vacations_employee_modo_idx'),
    ('0026_glorious_serpent_society','indice','','overtime_records_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','payroll_details_company_modo_idx'),
    ('0026_glorious_serpent_society','indice','','payrolls_company_modo_idx'),
    ('0027_faulty_lake','tabla','barcode_print_logs',''),
    ('0027_faulty_lake','tabla','product_barcodes',''),
    ('0027_faulty_lake','columna','company_settings','barcode_default_type'),
    ('0027_faulty_lake','columna','company_settings','barcode_prefix'),
    ('0027_faulty_lake','columna','company_settings','barcode_length'),
    ('0027_faulty_lake','restriccion','barcode_print_logs','barcode_print_logs_company_id_companies_id_fk'),
    ('0027_faulty_lake','restriccion','barcode_print_logs','barcode_print_logs_product_id_products_id_fk'),
    ('0027_faulty_lake','restriccion','barcode_print_logs','barcode_print_logs_user_id_users_id_fk'),
    ('0027_faulty_lake','restriccion','product_barcodes','product_barcodes_company_id_companies_id_fk'),
    ('0027_faulty_lake','restriccion','product_barcodes','product_barcodes_product_id_products_id_fk'),
    ('0027_faulty_lake','indice','','barcode_print_logs_company_idx'),
    ('0027_faulty_lake','indice','','barcode_print_logs_product_idx'),
    ('0027_faulty_lake','indice','','prod_barcodes_company_idx'),
    ('0027_faulty_lake','indice','','prod_barcodes_product_idx'),
    ('0027_faulty_lake','indice','','prod_barcodes_barcode_idx'),
    ('0028_foamy_iron_fist','tabla','supplier_order_lines',''),
    ('0028_foamy_iron_fist','tabla','supplier_order_sequences',''),
    ('0028_foamy_iron_fist','tabla','supplier_orders',''),
    ('0028_foamy_iron_fist','restriccion','supplier_order_lines','supplier_order_lines_order_id_supplier_orders_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_order_lines','supplier_order_lines_product_id_products_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_order_sequences','supplier_order_sequences_company_id_companies_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_orders','supplier_orders_company_id_companies_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_orders','supplier_orders_supplier_id_suppliers_id_fk'),
    ('0028_foamy_iron_fist','restriccion','supplier_orders','supplier_orders_user_id_users_id_fk'),
    ('0028_foamy_iron_fist','indice','','supplier_order_lines_order_idx'),
    ('0028_foamy_iron_fist','indice','','supplier_order_seq_company_year_modo_idx'),
    ('0028_foamy_iron_fist','indice','','supplier_orders_company_num_modo_idx'),
    ('0028_foamy_iron_fist','indice','','supplier_orders_status_idx'),
    ('0028_foamy_iron_fist','indice','','supplier_orders_supplier_idx'),
    ('0029_add_checks_cleared_date','columna','checks','cleared_date'),
    ('0029_add_checks_cleared_date','indice','','checks_cleared_date_idx'),
    ('0030_reconciliacion','tabla','expense_types',''),
    ('0030_reconciliacion','tabla','agent_proposals',''),
    ('0030_reconciliacion','tabla','document_shares',''),
    ('0030_reconciliacion','tabla','system_email_logs',''),
    ('0030_reconciliacion','tabla','purchase_orders',''),
    ('0030_reconciliacion','tabla','purchase_order_items',''),
    ('0030_reconciliacion','tabla','purchase_order_logs',''),
    ('0030_reconciliacion','columna','accounts_payable','expense_id'),
    ('0030_reconciliacion','columna','accounts_payable','purchase_order_id'),
    ('0030_reconciliacion','columna','companies','phone'),
    ('0030_reconciliacion','columna','customers','price_type'),
    ('0030_reconciliacion','columna','products','is_on_sale'),
    ('0030_reconciliacion','columna','products','promotional_price'),
    ('0030_reconciliacion','columna','route_mappings','is_menu_item'),
    ('0030_reconciliacion','columna','route_mappings','display_name'),
    ('0030_reconciliacion','columna','route_mappings','group_name'),
    ('0030_reconciliacion','columna','route_mappings','icon_name'),
    ('0030_reconciliacion','columna','route_mappings','order_index'),
    ('0030_reconciliacion','restriccion','accounts_payable','accounts_payable_purchase_order_id_purchase_orders_id_fk'),
    ('0030_reconciliacion','restriccion','expense_types','expense_types_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','system_email_logs','system_email_logs_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','system_email_logs','system_email_logs_user_id_users_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_order_items','purchase_order_items_purchase_order_id_purchase_orders_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_order_items','purchase_order_items_product_id_products_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_order_logs','purchase_order_logs_purchase_order_id_purchase_orders_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_order_logs','purchase_order_logs_user_id_users_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_orders','purchase_orders_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_orders','purchase_orders_supplier_id_suppliers_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_orders','purchase_orders_warehouse_id_warehouses_id_fk'),
    ('0030_reconciliacion','restriccion','purchase_orders','purchase_orders_created_by_users_id_fk'),
    ('0030_reconciliacion','restriccion','agent_proposals','agent_proposals_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','agent_proposals','agent_proposals_user_id_users_id_fk'),
    ('0030_reconciliacion','restriccion','document_shares','document_shares_company_id_companies_id_fk'),
    ('0030_reconciliacion','restriccion','document_shares','document_shares_created_by_users_id_fk'),
    ('0030_reconciliacion','restriccion','accounts_payable','accounts_payable_expense_id_expenses_id_fk'),
    ('0030_reconciliacion','indice','','expense_types_company_code_idx'),
    ('0030_reconciliacion','indice','','expense_types_company_idx'),
    ('0030_reconciliacion','indice','','system_email_logs_company_idx'),
    ('0030_reconciliacion','indice','','system_email_logs_context_idx'),
    ('0030_reconciliacion','indice','','system_email_logs_status_idx'),
    ('0030_reconciliacion','indice','','purchase_order_items_order_idx'),
    ('0030_reconciliacion','indice','','purchase_order_logs_order_idx'),
    ('0030_reconciliacion','indice','','purchase_orders_company_num_modo_idx'),
    ('0030_reconciliacion','indice','','purchase_orders_status_idx'),
    ('0030_reconciliacion','indice','','purchase_orders_supplier_idx'),
    ('0030_reconciliacion','indice','','agent_proposals_company_modo_idx'),
    ('0030_reconciliacion','indice','','agent_proposals_area_idx'),
    ('0031_inventario_no_negativo','restriccion','inventory_levels','chk_inventory_no_negativo')
),
existente AS (
  SELECT 'tabla' AS tipo, table_name::text AS tabla, '' AS nombre
  FROM information_schema.tables WHERE table_schema = 'public'
  UNION ALL
  SELECT 'columna', table_name::text, column_name::text
  FROM information_schema.columns WHERE table_schema = 'public'
  UNION ALL
  SELECT 'restriccion', rel.relname::text, con.conname::text
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = rel.relnamespace AND n.nspname = 'public'
  UNION ALL
  SELECT 'indice', '', indexname::text
  FROM pg_indexes WHERE schemaname = 'public'
  UNION ALL
  SELECT 'tipo', typname::text, ''
  FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace AND n.nspname = 'public'
)
SELECT e.migracion,
       count(*) FILTER (WHERE NOT EXISTS (
         SELECT 1 FROM existente r
         WHERE r.tipo = e.tipo AND lower(r.tabla) = lower(e.tabla)
           AND lower(r.nombre) = lower(e.nombre))) AS faltan,
       count(*) AS declara
FROM esperado e
GROUP BY e.migracion
HAVING count(*) FILTER (WHERE NOT EXISTS (
         SELECT 1 FROM existente r
         WHERE r.tipo = e.tipo AND lower(r.tabla) = lower(e.tabla)
           AND lower(r.nombre) = lower(e.nombre))) > 0
ORDER BY e.migracion;
